
package com.yuanxin.app.app.wsdl.wcf;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IApplicationService", targetNamespace = "http://ws.easc.net/ApplicationService")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IApplicationService {


    /**
     * 
     * @param request
     * @return
     *     returns cn.penglui.ws.client.wcf.AppResponse
     */
    @WebMethod(operationName = "GetAppinfo", action = "http://ws.easc.net/ApplicationService/IApplicationService/GetAppinfo")
    @WebResult(name = "GetAppinfoResult", targetNamespace = "http://ws.easc.net/ApplicationService")
    @RequestWrapper(localName = "GetAppinfo", targetNamespace = "http://ws.easc.net/ApplicationService", className = "cn.penglui.ws.client.wcf.GetAppinfo")
    @ResponseWrapper(localName = "GetAppinfoResponse", targetNamespace = "http://ws.easc.net/ApplicationService", className = "cn.penglui.ws.client.wcf.GetAppinfoResponse")
    public AppResponse getAppinfo(
        @WebParam(name = "request", targetNamespace = "http://ws.easc.net/ApplicationService")
        AppRequest request);

    /**
     * 
     * @param userName
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetUserDynamic", action = "http://ws.easc.net/ApplicationService/IApplicationService/GetUserDynamic")
    @WebResult(name = "GetUserDynamicResult", targetNamespace = "http://ws.easc.net/ApplicationService")
    @RequestWrapper(localName = "GetUserDynamic", targetNamespace = "http://ws.easc.net/ApplicationService", className = "cn.penglui.ws.client.wcf.GetUserDynamic")
    @ResponseWrapper(localName = "GetUserDynamicResponse", targetNamespace = "http://ws.easc.net/ApplicationService", className = "cn.penglui.ws.client.wcf.GetUserDynamicResponse")
    public String getUserDynamic(
        @WebParam(name = "userName", targetNamespace = "http://ws.easc.net/ApplicationService")
        String userName);

    /**
     * 
     * @param request
     */
    @WebMethod(operationName = "WriteLog", action = "http://ws.easc.net/ApplicationService/IApplicationService/WriteLog")
    @RequestWrapper(localName = "WriteLog", targetNamespace = "http://ws.easc.net/ApplicationService", className = "cn.penglui.ws.client.wcf.WriteLog")
    @ResponseWrapper(localName = "WriteLogResponse", targetNamespace = "http://ws.easc.net/ApplicationService", className = "cn.penglui.ws.client.wcf.WriteLogResponse")
    public void writeLog(
        @WebParam(name = "request", targetNamespace = "http://ws.easc.net/ApplicationService")
        AuditLogRequest request);

    /**
     * 
     * @param getAuditLogsResult
     * @param pageCount
     * @param endDate
     * @param pageIndex
     * @param appId
     * @param operateType
     * @param pageSize
     * @param appFunctionId
     * @param user
     * @param startDate
     */
    @WebMethod(operationName = "GetAuditLogs", action = "http://ws.easc.net/ApplicationService/IApplicationService/GetAuditLogs")
    @RequestWrapper(localName = "GetAuditLogs", targetNamespace = "http://ws.easc.net/ApplicationService", className = "cn.penglui.ws.client.wcf.GetAuditLogs")
    @ResponseWrapper(localName = "GetAuditLogsResponse", targetNamespace = "http://ws.easc.net/ApplicationService", className = "cn.penglui.ws.client.wcf.GetAuditLogsResponse")
    public void getAuditLogs(
        @WebParam(name = "user", targetNamespace = "http://ws.easc.net/ApplicationService")
        String user,
        @WebParam(name = "startDate", targetNamespace = "http://ws.easc.net/ApplicationService")
        String startDate,
        @WebParam(name = "endDate", targetNamespace = "http://ws.easc.net/ApplicationService")
        String endDate,
        @WebParam(name = "operateType", targetNamespace = "http://ws.easc.net/ApplicationService")
        Long operateType,
        @WebParam(name = "pageIndex", targetNamespace = "http://ws.easc.net/ApplicationService")
        Integer pageIndex,
        @WebParam(name = "pageSize", targetNamespace = "http://ws.easc.net/ApplicationService")
        Integer pageSize,
        @WebParam(name = "appId", targetNamespace = "http://ws.easc.net/ApplicationService")
        String appId,
        @WebParam(name = "appFunctionId", targetNamespace = "http://ws.easc.net/ApplicationService")
        String appFunctionId,
        @WebParam(name = "GetAuditLogsResult", targetNamespace = "http://ws.easc.net/ApplicationService", mode = WebParam.Mode.OUT)
        Holder<ArrayOfSeAuditLog> getAuditLogsResult,
        @WebParam(name = "pageCount", targetNamespace = "http://ws.easc.net/ApplicationService", mode = WebParam.Mode.OUT)
        Holder<Integer> pageCount);

}
